### ISSUE TITLE
Bug when downsampling 128x32 image

### ISSUE THREAD

**Issue by ShabbyX** [GPUOpen-Effects/FidelityFX-SPD#2]
I'm integrating this SPD into [ANGLE](angleproject.org), and writing tests, I'm seeing a bug in this code. I'm testing on Linux with an Nvidia Geforce GTX 970 on driver 440.100. (I see bigger issues with Intel/mesa too, but I can't be sure they aren't driver bugs).

If the source image has a base size of 128x32 that is all red, using a sampler that clamps to edges, I can see mips 1 through 6 becoming all red (which is correct) and mip 7 (the last 1x1 mip) becoming half-red (as in `vec4(0.5, 0, 0, 0.5)`).

The last mip is indeed written to, so there aren't any errors with the atomic counter buffer. To make sure the bug is in this library, I made `SpdLoadSourceImage` even directly return a constant red:

```
AF4 SpdLoadSourceImage(ASU2 p)
{
    return AF4(1.0, 0.0, 0.0, 1.0);
}
```

And I still see the last mip being half-red. Additionally, I made `SpdLoad` return red:

```
AF4 SpdLoad(ASU2 p)
{
    return AF4(1.0, 0.0, 0.0, 1.0);
}
```

And that fixes the issue. Is it possible that the library is trying to load outside the image coordinates? That could explain why transparent-black is returned, turning red into half-red.

The rest of the glue code exactly follows the instructions. For completeness, here's the relevant part of the shader:

```
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba32f) uniform coherent image2D dst[12];
layout(set = 0, binding = 1) uniform sampler2D src;
layout(set = 0, binding = 2) coherent buffer GlobalAtomic
{
    uint counter;
} globalAtomic;

layout(push_constant) uniform PushConstants {
    uint levelCount;
    uint numWorkGroups;
    vec2 invSrcExtent;
} params;

#define A_GPU
#define A_GLSL

#include "third_party/ffx_spd/ffx_a.h"

shared AF4 spd_intermediate[16][16];
shared AU1 spd_counter;

#define SPD_NO_WAVE_OPERATIONS
#define SPD_LINEAR_SAMPLER

AF4 SpdLoadSourceImage(ASU2 p)
{
    // Hack: return red to verify the bug
    return AF4(1.0, 0.0, 0.0, 1.0);
    //AF2 textureCoord = p * params.invSrcExtent + params.invSrcExtent;
    //return texture(src, textureCoord);
}

AF4 SpdLoad(ASU2 p)
{
    return imageLoad(dst[5], p);
}

void SpdStore(ASU2 p, AF4 value, AU1 mip)
{
    imageStore(dst[mip], p, value);
}

AF4 SpdLoadIntermediate(AU1 x, AU1 y)
{
    return spd_intermediate[x][y];
}
void SpdStoreIntermediate(AU1 x, AU1 y, AF4 value)
{
    spd_intermediate[x][y] = value;
}

AF4 SpdReduce4(AF4 v0, AF4 v1, AF4 v2, AF4 v3)
{
    return (v0 + v1 + v2 + v3) * 0.25;
}

void SpdIncreaseAtomicCounter()
{
    spd_counter = atomicAdd(globalAtomic.counter, 1);
}
AU1 SpdGetAtomicCounter()
{
    return spd_counter;
}

#include "third_party/ffx_spd/ffx_spd.h"

void main()
{
    SpdDownsample(gl_WorkGroupID.xy, gl_LocalInvocationIndex,
            params.levelCount, params.numWorkGroups);
}
```

The issue is present with 128x64 and 128x127 textures too, but not 128x128.

**Comment by ShabbyX** [comment]
I further took a look at the code, and there's something I don't quite follow. `SpdDownsampleMips_6_7` is writing to the last mip 4 times, even though it's 1x1. If I comment out the rest of that function after the first `SpdStore`, I see correct results in the last mip.

Indeed, shouldn't the `if (mips <= 7) return;` line in that function be right after the first `SpdStore`?

**Comment by ShabbyX** [comment]
To confirm my suspicion that the issue is loading outside image coordinates, I changed `SpdLoad` as such:

```
AF4 SpdLoad(ASU2 p)
{
    return imageLoad(dst[5], ASU2(0, 0));
}
```

This makes the test pass. And if I change it as such:

```
AF4 SpdLoad(ASU2 p)
{
    return imageLoad(dst[5], ASU2(1, 1));
}
```

I see transparent black in the last mip. Note that the mip before last in this test is 2x1.

**Comment by aurolou** [comment]
Hi,
Indeed, Spd does not check if the Loads are out of bounds - it's up to the user to add controlled border handling. Spd in general has no information about the texture size and the load and store functions, as this is done on the integration side.
So for your problem, you would need to add border control in the SpdLoad function - and if it's an out-of-bounds load manually clamp your coordinates back in-to-bounds for example, or return a constant value.

And yes, in SpdDownsampleMips_6_7, every thread computes 4 output values for Mip 6 (same as every thread computes 4 output values for the first output Mip). Otherwise downsampling a texture of size 4096x4096 would not work. Again, this can be caught with added border control handling in the store function though.

But I agree that the sample does not show case this, it's only mentioned in the docs :) I'll make a note of it! Thanks for the report. :)

**Comment by ShabbyX** [comment]
Thank you for the information. I opted to limit the mips to 6 and avoid this issue, then generate mipmaps 6 mips at a time:

- On devices where `maxPerStageDescriptorStorageImages` is 4 (common on Android), mipmaps can only be generated 4 at a time anyway.
- Limiting to 6 means I can get rid of the atomic counter, slightly optimizing the mip generation.
- OOB image writes should already be a noop on most (all?) hardware
