### ISSUE TITLE
Project isn't single entrypoint utility function as claimed, its an app

### ISSUE THREAD

**Issue by adv-sw** [GPUOpen-Effects/FidelityFX-SPD#3]
A few changes to morph it towards more generic external use, which I hope are helpful.

https://github.com/adv-sw/FidelityFX-SPD

Realise you have a GPU API. This adds a CPU API to improve the usefulness of the project.

Can still compile app mode & run it just the way you had everything before AND as a library now.

All yours - please consider merging into master as there's no need for this to fragment.

**Comment by adv-sw** [comment]
Also in SPDCS.cpp  void SPDCS::Draw(ID3D12GraphicsCommandList2 *pCommandList)

To morph from hardwired cubemap processing to generic texture solve 

https://pastebin.com/V0Wa8Y4t

& have renamed the cubemap texture m_texture & made it a pointer so its generic utility allowing us to pass in whatever texture we want processing.

Thank you for your consideration. Haven't tested this with a non-cubemap yet as still working on morphing into a form whereby I can do that.

**Comment by rys** [comment]
Hi @adv-sw, thanks for proposing the changes but unfortunately it's not something we plan to bring into the project. Sorry for taking so long to get back to you too, I shouldn't have left you hanging.
